# This file lists the dependencies needed to build and test all of echemdb-app.
# Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment.yaml
name: echemdb_app
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy>=1.26.4,<2.0.0
  - pip>=24
  - streamlit>=1.36.0,<2.0.0
  - unitpackage>=0.8.4,<0.9.0
  - pip:
    - streamlit-extras>=0.4.3,<1.0.0
    - streamlit-navigation-bar>=3.3.0,<3.4.0
